# Generated by Django 5.2 on 2025-04-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuchar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cislo', models.CharField(blank=True, max_length=20, null=True)),
                ('popis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('cas_na_pripravu', models.PositiveIntegerField(help_text='čas v minutách')),
                ('kuchar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepty', to='recepty.kuchar')),
            ],
        ),
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('znamka', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoceni', to='recepty.recept')),
            ],
        ),
    ]
