# Generated by Django 5.2 on 2025-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='popis',
            new_name='obsah',
        ),
        migrations.RemoveField(
            model_name='kuchar',
            name='cislo',
        ),
        migrations.RemoveField(
            model_name='kuchar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kuchar',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='cas_na_pripravu',
        ),
        migrations.AddField(
            model_name='kuchar',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='autori/'),
        ),
        migrations.AddField(
            model_name='recept',
            name='doba_pripravy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recept',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='obalky/'),
        ),
        migrations.AddField(
            model_name='recept',
            name='kategorie',
            field=models.ManyToManyField(to='recepty.kategorie'),
        ),
        migrations.DeleteModel(
            name='Hodnoceni',
        ),
    ]
